PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX cvgo: <http://www.semanticweb.org/dapi/ontologies/2019/11/ComputerVideoGameOntology#>
PREFIX vgo:  <http://purl.org/net/VideoGameOntology#>

SELECT ?title
WHERE {
    ?feature cvgo:isFeatureOfGame ?game .
    ?tag cvgo:isTagOfGame ?game .
    ?genre cvgo:isGenreOfGame ?game .
    ?game cvgo:title ?title .

    ?feature cvgo:featureName ?featureName .
    ?tag cvgo:tagName ?tagName .
    ?genre cvgo:genreName ?genreName .

    FILTER(?featureName IN ("Multi-player"))
    FILTER(?tagName IN ("Competitive"))
    FILTER(?genreName IN ("Action"))
}
GROUP BY ?title