PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX cvgo: <http://www.semanticweb.org/dapi/ontologies/2019/11/ComputerVideoGameOntology#>
PREFIX vgo:  <http://purl.org/net/VideoGameOntology#>

SELECT ?name (GROUP_CONCAT (?title;separator = ", ") AS ?games) (COUNT(?game) AS ?total)
WHERE {
    ?developer cvgo:developerName ?name .
    OPTIONAL { 
        ?developer cvgo:developsGame ?game .
        ?game cvgo:title ?title
    }
}
GROUP BY ?name
ORDER BY DESC(?total)